basic_settings:
  title: 325 Studio
  phone: (385) 503-3663 
  logo: 
  logo-width:
  location: "Salt Lake City, Utah"
  google_analytics: UA-412496-3

menu_settings:
  - title: "Home"
    url: "/"
  # - title: "Services"
  #   url: "/services/"
  #   sublinks:
  #   - title: "Website Design"
  #     url: "/website-design/"
  #   - title: "App Design"
  #     url: "/app-design/"
  #   - title: "Logo Design"
  #     url: "/logo-design/"
  # - title: "Projects"
  #   url: "#projects"
  - title: "About"
    url: "/about/"
  # - title: "Contact"
  #   url: "/contact/"

font_settings:
  font_embed: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700&family=Mulish:wght@300;400;500;700&display=swap" 
  title_font: 'Mulish'
  body_font: 'Inter'

# Custom Navbar Colors
navbar_colors:
  bg: "rgba(255, 255, 255, .96)"
  menu_color: "#000000"
  menu_hover_color: "#000000"
  active_color: "#000000"
  menu_color: "#000000"
  brand_menu_color: "#000000"
  brand_menu_hover_color: "#000000"

# Background color for the call to action box
cta:
  bg: "linear-gradient(155deg, rgba(69,56,133,1) 0%, rgba(35,55,89,0.6) 100%);"

# Background color for the form submission box 
form: 
  bg: "#229155"

social_settings:
  facebook_url: 'https://www.facebook.com/325studio/'
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  medium_url: ''
  dribbble_url: ''
  github_url: ''
  linkedin_url: ''